package middleware

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"net/http"
	"strings"

	"github.com/jozefvalachovic/logger/v4"
)

const (
	// TraceparentHeader is the W3C Trace Context propagation header.
	TraceparentHeader = "Traceparent"
	// TracestateHeader carries vendor-specific trace data.
	TracestateHeader = "Tracestate"

	traceparentVersion = "00"
	traceIDLen         = 16 // 16 bytes = 32 hex chars
	spanIDLen          = 8  // 8 bytes  = 16 hex chars
)

// TraceContextConfig configures the TraceContext middleware.
// All fields are optional; the zero value enables full propagation with
// auto-generated identifiers.
type TraceContextConfig struct {
	// Disabled turns off trace-context propagation entirely.
	// Default: false (enabled).
	Disabled bool
}

// TraceInfo holds the parsed W3C Trace Context identifiers.
type TraceInfo struct {
	// TraceID is the 32-hex-char trace identifier shared across the full
	// distributed call chain.
	TraceID string
	// SpanID is the 16-hex-char span identifier generated by this service.
	SpanID string
	// ParentSpanID is the 16-hex-char span identifier received from the
	// incoming traceparent header. Empty when the trace was initiated here.
	ParentSpanID string
	// TraceFlags is the 2-hex-char flags field (e.g. "01" = sampled).
	TraceFlags string
	// TraceState is the raw tracestate header value, passed through unchanged.
	TraceState string
}

type traceContextKey int

const traceInfoKey traceContextKey = iota

// TraceInfoFromContext returns the TraceInfo stored in the request context, or
// a zero value when trace-context propagation is disabled or absent.
func TraceInfoFromContext(r *http.Request) TraceInfo {
	v, _ := r.Context().Value(traceInfoKey).(TraceInfo)
	return v
}

// TraceContext implements W3C Trace Context propagation (traceparent /
// tracestate headers).
//
// If the incoming request carries a valid traceparent header, the trace-id and
// flags are preserved and a new span-id is generated for this service's span.
// If absent or malformed, a brand-new trace-id and span-id are generated.
//
// The tracestate header is passed through unchanged.
//
// The TraceInfo is stored in the request context (retrieve with
// TraceInfoFromContext) and the response traceparent header is set so
// downstream clients can continue the trace.
func TraceContext(cfgs ...TraceContextConfig) func(http.Handler) http.Handler {
	cfg := TraceContextConfig{}
	if len(cfgs) > 0 {
		cfg = cfgs[0]
	}
	if cfg.Disabled {
		return func(next http.Handler) http.Handler { return next }
	}

	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			info := parseTraceparent(r.Header.Get(TraceparentHeader))
			info.TraceState = r.Header.Get(TracestateHeader)

			ctx := context.WithValue(r.Context(), traceInfoKey, info)

			// Enrich the request-scoped logger with trace identifiers.
			child := logger.FromContext(ctx).With("traceId", info.TraceID, "spanId", info.SpanID)
			ctx = logger.NewContext(ctx, child)

			r = r.WithContext(ctx)

			// Set response headers so the next hop can continue the trace.
			w.Header().Set(TraceparentHeader, formatTraceparent(info))
			if info.TraceState != "" {
				w.Header().Set(TracestateHeader, info.TraceState)
			}

			next.ServeHTTP(w, r)
		})
	}
}

// parseTraceparent parses a W3C traceparent header value.
// Returns a TraceInfo with a new span-id. If the header is absent or
// malformed, a fresh trace-id is generated as well.
func parseTraceparent(header string) TraceInfo {
	newSpan := generateSpanID()

	if header == "" {
		return TraceInfo{
			TraceID:    generateTraceID(),
			SpanID:     newSpan,
			TraceFlags: "00",
		}
	}

	// Expected format: {version}-{trace-id}-{parent-id}-{trace-flags}
	// Example: 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01
	parts := strings.Split(header, "-")
	if len(parts) != 4 {
		return TraceInfo{
			TraceID:    generateTraceID(),
			SpanID:     newSpan,
			TraceFlags: "00",
		}
	}

	version, traceID, parentID, flags := parts[0], parts[1], parts[2], parts[3]

	if len(version) != 2 || !isLowerHex(version) ||
		len(traceID) != 32 || !isLowerHex(traceID) || isAllZero(traceID) ||
		len(parentID) != 16 || !isLowerHex(parentID) || isAllZero(parentID) ||
		len(flags) != 2 || !isLowerHex(flags) {
		return TraceInfo{
			TraceID:    generateTraceID(),
			SpanID:     newSpan,
			TraceFlags: "00",
		}
	}

	return TraceInfo{
		TraceID:      traceID,
		SpanID:       newSpan,
		ParentSpanID: parentID,
		TraceFlags:   flags,
	}
}

func formatTraceparent(info TraceInfo) string {
	return traceparentVersion + "-" + info.TraceID + "-" + info.SpanID + "-" + info.TraceFlags
}

func generateTraceID() string {
	b := make([]byte, traceIDLen)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

func generateSpanID() string {
	b := make([]byte, spanIDLen)
	_, _ = rand.Read(b)
	return hex.EncodeToString(b)
}

// isLowerHex reports whether s contains only lowercase hex digits.
func isLowerHex(s string) bool {
	for i := range len(s) {
		c := s[i]
		if (c < '0' || c > '9') && (c < 'a' || c > 'f') {
			return false
		}
	}
	return true
}

// isAllZero reports whether s is all '0' characters (invalid per W3C spec).
func isAllZero(s string) bool {
	for i := range len(s) {
		if s[i] != '0' {
			return false
		}
	}
	return true
}
